Made passengerlist activity layout file
bsoc-bitbyte/busify-android pull request #10
Opened 2023-06-17 13:45 UTC by sadvika05

## Overview

1. This PR fixes or fixes part of #6 .
2. This PR does the following: added search bar, bus cardview and recyclerview for passengerlist items
<img src=https://github.com/bsoc-bitbyte/busify-android/assets/128731424/5e5b85ad-73a9-426b-8707-7a81ccec39d2" width="30%" height="30%">

2023-06-17 19:59 UTC, AgPriyanshu18 requested changes
Give proper ID to all the views, refer to this [question](https://stackoverflow.com/questions/12870537/android-naming-convention)

2023-06-17 19:59 UTC, AgPriyanshu18 commented on app/src/main/res/layout/activity_passenger_list.xml
> +        android:textSize="48sp"
Do not use Textview, use ToolBar instead.
Always write constraint tags.

2023-06-17 19:59 UTC, AgPriyanshu18 commented on app/src/main/res/layout/activity_passenger_list.xml
> +                android:src="@drawable/search_icon"
You can use a search view instead. Refer [this](https://developer.android.com/reference/android/widget/SearchView).

2023-06-17 19:59 UTC, AgPriyanshu18 commented on app/src/main/res/layout/activity_passenger_list.xml
> +    <androidx.recyclerview.widget.RecyclerView
Add ID to the RecyclerView

2023-06-17 19:59 UTC, AgPriyanshu18 commented on app/src/main/res/layout/activity_passenger_list.xml
> +                    android:layout_height = "wrap_content"
Don't need to write the code for this view again.
It is similar to view, merged in this issue #3,
Use include to reuse the layouts, you can take reference from [here](https://developer.android.com/develop/ui/views/layout/improving-layouts/reusing-layouts)

2023-06-18 11:27 UTC, sadvika05 commented
I have made the changes
<img src="https://github.com/bsoc-bitbyte/busify-android/assets/128731424/352afd74-8734-4991-8b42-50cd82da2256">

2023-06-18 11:35 UTC, sadvika05 commented
I have made the changes.
<img src="https://github.com/bsoc-bitbyte/busify-android/assets/128731424/42034027-c4b4-4ff1-a7ca-9faac9df8f9d"
width="50%" height="50%">

2023-06-18 19:11 UTC, AgPriyanshu18 requested changes
Changes with include tags are fine, Fix issues with :
1. ToolBar
2. RecyclerView

2023-06-18 19:11 UTC, AgPriyanshu18 commented on app/src/main/res/layout/activity_passenger_list.xml
> +            android:layout_height="wrap_content"
It's not the correct way either, Use the title tag in the Toolbar Itself.  You don't need a TextView in ToolBar just to give it a Title.

2023-06-18 19:11 UTC, AgPriyanshu18 commented on app/src/main/res/layout/activity_passenger_list.xml
>              android:layout_height="wrap_content"
I think LinearLayout here is unnecessary, why are you using it here ?

2023-06-18 19:11 UTC, AgPriyanshu18 commented on app/src/main/res/layout/activity_passenger_list.xml
> +    <androidx.recyclerview.widget.RecyclerView
Add other 3 constraint tags also.
If you add only one for the top, on small screens it will go out of the screen from below.

2023-06-19 05:14 UTC, sadvika05 commented
made changes. But, If I use title tag in toolbar instead of text view, unable to change the size and font of title text without making another theme file to customize the text.
<img src="https://github.com/bsoc-bitbyte/busify-android/assets/128731424/ba436137-4c91-4cee-9177-8f0894de9d2d"
width="50%" height="50%">

2023-06-19 06:30 UTC, AgPriyanshu18 commented
Yes, you need to create a style for ToolBar, try to create one.
You can refer [this ](https://stackoverflow.com/questions/26577528/android-toolbar-style)

2023-06-19 11:18 UTC, sadvika05 commented
Agrim has added the style file and pushed his code so I have just set the titleTextAppearance to what he has made instead of making my own style file to make everything consistent.

2023-06-19 12:56 UTC, AgPriyanshu18 approved these changes

2023-06-19 12:57 UTC, merged