Readme
bsoc-bitbyte/busify-android pull request #4
Opened 2023-06-14 12:10 UTC by Adi8712

## Overview
Added the readme.md file consisting of demo ui, tech stack, installation, features sections
Renamed to AppConstantts.kt to AppConstants.kt file

2023-06-14 18:18 UTC, PraneGIT requested changes
@Adi8712 
In  Text Stack section :
remove lines 16,17,
Elaborate on Architecture,
fix viewModel description

2023-06-14 20:30 UTC, Adi8712 commented
@PraneGIT I have made the necessary changes to the readme

2023-06-15 07:17 UTC, PraneGIT approved these changes

2023-06-15 07:18 UTC, merged

2023-07-04 07:17 UTC, Adi8712 commented
@AgPriyanshu18 @PraneGIT kindly assign labels on all the prs just like the issues in accordance to the bitbyte evaluation process